### ISSUE TITLE
Better screenshots

### ISSUE THREAD

**Issue by AlexNodex** [amitmerchant1990/responsive-project-landing-page#1]
Would you like better screenshots?

I am quite happy to do this for you.

**Comment by amitmerchant1990** [comment]
Yes sure. I would like to see.

**Comment by AlexNodex** [comment]
what sizes would you like?

Would you also like retina sizes?

**Comment by amitmerchant1990** [comment]
All the sizes you could get(including retina). Thanks!

**Comment by AlexNodex** [comment]
I need specific resolutions.

**Comment by amitmerchant1990** [comment]
Would be good to have `1600x1200`, `1920x1080`, `3840x2160` and so forth.

**Comment by AlexNodex** [comment]
Please explain what so forth is.

My screenshot program requires specific resolutions so I need you to explicitly define those for me.

**Comment by amitmerchant1990** [comment]
I have given you all the resolutions I'm aware about. Now, it's upto you which one you provide.

**Comment by AlexNodex** [comment]
So you don't want anything for tablet or mobile phone resolution ?

**Comment by amitmerchant1990** [comment]
@Alex I gave up on this. You can just provide the resolutions you think would be best to demonstrate this landing page. It's as simple as this. Or else, I'll close this.

**Comment by AlexNodex** [comment]
Close it, do your own screenshots. 

You are hard work, I asked two simple questions that you can't even answer

**Comment by amitmerchant1990** [comment]
`750x1334`, `720x1280`, `800x1280`, `1600x1200`, `1920x1080`, `3840x2160` are least I can get. These are final resolutions I want.

**Comment by AlexNodex** [comment]
As I said, close the ticket and do your own screenshots, your attitude toward someone trying to help us not one I want to be associated with.

Best of luck for the project

**Comment by amitmerchant1990** [comment]
Thanks.
